[project]
name = "OpenQueryBI-MCP"
version = "0.1.0"
description = "This MCP tool helps LLMs to create Dashboards, tables and others in StreamLit throught connection with databases."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.0",
    "streamlit>=1.45.1",
]